#!/bin/bash
set -euo pipefail

XCODE_PROJECT="$1"
OUTPUT_FILE="$2"

# Extract MARKETING_VERSION and CURRENT_PROJECT_VERSION
MARKETING_VERSION=$(grep -m 1 "MARKETING_VERSION = " "$XCODE_PROJECT" | sed 's/.*MARKETING_VERSION = \(.*\);/\1/' | tr -d ' ;')
CURRENT_PROJECT_VERSION=$(grep -m 1 "CURRENT_PROJECT_VERSION = " "$XCODE_PROJECT" | sed 's/.*CURRENT_PROJECT_VERSION = \(.*\);/\1/' | tr -d ' ;')

# Write to output file
cat > "$OUTPUT_FILE" << EOF
MARKETING_VERSION=$MARKETING_VERSION
CURRENT_PROJECT_VERSION=$CURRENT_PROJECT_VERSION
EOF

echo "Extracted versions: $MARKETING_VERSION ($CURRENT_PROJECT_VERSION)" >&2