name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    name: CI Pipeline
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
    
    - name: Install just
      run: brew install just
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Configure macro package trust
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
    
    - name: Resolve Swift Package Dependencies
      run: swift package resolve
    
    - name: Lint
      run: just lint
    
    - name: Build
      run: just build
    
    - name: Build iOS
      run: just build-ios
    
    - name: Test
      run: just test