name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install just
      run: brew install just
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run Lint
      run: just lint

  build:
    name: Build
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26'
    
    - name: Install just
      run: brew install just
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Configure macro package trust
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
    
    - name: Resolve Swift Package Dependencies
      run: swift package resolve
    
    - name: Run Build
      run: just build

  build-ios:
    name: Build iOS
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26'
    
    - name: Install just
      run: brew install just
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Configure macro package trust
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
    
    - name: Resolve Swift Package Dependencies
      run: swift package resolve
    
    - name: Run Build iOS
      run: just build-ios

  test:
    name: Test
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26'
    
    - name: Install just
      run: brew install just
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Configure macro package trust
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
    
    - name: Resolve Swift Package Dependencies
      run: swift package resolve
    
    - name: Run Tests
      run: just test